### ISSUE TITLE
Use lowercase f in formatting function names

### ISSUE THREAD

**Issue by chr4** [apsdehal/go-logger#17]
Your project looks really nice!

When reading the examples, I propose to streamline function names to correspond to the naming scheme of `fmt`, `log`  and `testing`: `fmt.Printf()`, `log.Printf()`, `t.Errorf()` are all using lowercase `f`, whereas your package uses `WarningF()` `DebugF()` with capital `F`s.

Proposal: Use lowercase `f` in your package as well, e.g. `Warningf()`

**Comment by apsdehal** [comment]
We have them already. See https://github.com/apsdehal/go-logger/blob/master/logger.go#L356 and related functions. Closing for now as "already exists".
