### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by tigerclawn82** [apsdehal/go-logger#5]
I want to use [Sourcegraph](https://sourcegraph.com) for go-logger code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/apsdehal/go-logger. (It should only take 30 seconds.)

Thank you!

**Comment by apsdehal** [comment]
Hey, I have enabled the sourcegraph. It is building right now.

Thanks.
